version: "3.8"
    inference:
        container_name: "yolov5"
        build: "./backbone"
        environment:
            - PORT=5000
            - MODEL_PATH=weights/best.pt
        ports:
            - '5000:5000'
        command: "python3 app.py"
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]

    train:
        container_name: "yolov5-train"
        build: "./train"
        environment:
            - PORT=5001
        ports:
            - '8000:8000'
        command: "python3 main_train.py"
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
